apiVersion: v1
kind: Service
metadata:
  name: {{ include "ml-model.fullname" . }}
  labels:
    app: {{ include "ml-model.name" . }}
    chart: {{ include "ml-model.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
      {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  selector:
    app: {{ include "ml-model.name" . }}
    release: {{ .Release.Name }}
